services:
  db:
    image: postgres:15-alpine
    container_name: meguru-postgres
    environment:
      POSTGRES_DB: meguru_db
      POSTGRES_USER: meguru_user
      POSTGRES_PASSWORD: meguru_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meguru_user -d meguru_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - meguru-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: meguru-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://meguru_user:meguru_password@db:5432/meguru_db?sslmode=disable
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    volumes:
      - .:/app
    networks:
      - meguru-network

volumes:
  postgres_data:

networks:
  meguru-network:
    driver: bridge 